version: '3'

services:
  oskari-web:
    container_name: oskari-web
    hostname: oskari-web
    image: itryapitsin/oskari-web
    volumes:
    - ./oskari-logs:/opt/oskari/logs
    - ./oskari/oskari-server:/opt/oskari/oskari-server
    ports:
      - 8080:8080
    entrypoint: bash /opt/oskari/start.sh
    depends_on:
      - oskari-db
      - oskari-redis

  cors-proxy:
    build:
      context: ./Docker
      dockerfile: ./cors-proxy.dockerfile
    ports:
    - 80:80

  oskari-redis:
    image: redis:alpine
    container_name: oskari-redis
    hostname: oskari-redis
    ports:
      - 6379:6379

  oskari-db:
    container_name: oskari-db
    hostname: oskari-db
#    image: itryapitsin/oskari-db
    build:
      context: .
      dockerfile: ./Docker/db.dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
    volumes:
    - ./db/logs:/var/log/postgresql
    - ./db/data:/var/lib/postgresql

